### ISSUE TITLE
TypeError: 'NoneType' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by RossMelbourne** [caiogranero/google-custom-search-api-python#2]
All I changed in your code was the developerKey and the CSE cx= to a custom search engine I have defined and I am receiving the following error.  I am trying to scrape images from Google images and I thought you code was a good place to start.  Thank you!

(darkflow_env) Rosss-MBP:darkflow rossmelbourne$ python2 /Users/rossmelbourne/google-api-python-client/samples/customsearch/custom_image_search.py
Reading page number: 1
Traceback (most recent call last):
  File "/Users/rossmelbourne/google-api-python-client/samples/customsearch/custom_image_search.py", line 39, in <module>
    main()
  File "/Users/rossmelbourne/google-api-python-client/samples/customsearch/custom_image_search.py", line 34, in main
    startIndex = response[nPage].get("queries").get("nextPage")[0].get("startIndex")
TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by caiogranero** [comment]
Can you tell if the google api are returning all the data? Maybe your key are invalid or something like that and my code aren't prepare for this kind of error.
